### ISSUE TITLE
Create new Site Content Type Two Name Fields

### ISSUE THREAD

**Issue by itsknob** [ypcode/sp-site-designs-studio#1]
The Create New Site Content Type form in the Site Script creator has two fields for Name. The first is the "name" field, and the second should be the "description" field. 

The second field in the form should be "Description"
![image](https://user-images.githubusercontent.com/8973405/41928432-2be840aa-7943-11e8-9ddc-8d7bfec1e3f8.png)

This was the Site Design Studio v1.2.0.0

**Comment by itsknob** [comment]
My apologies. The issue is not present in this repository, I have moved this to the sp-dev-solutions repository. The issue can be found [here.](https://github.com/SharePoint/sp-dev-solutions/issues/24)

**Comment by ypcode** [comment]
Indeed this one is no longer maintained, I’ll delete it :) but thx for reporting :)

Cordialement
Yannick Plenevaux
________________________________
